# Generated by Django 5.0.14 on 2026-03-16 09:52


from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [TrigramExtension()
    ]
